//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1071 with alias "banner"
	/// <summary>Banner</summary>
	public partial interface IBanner : IPublishedContent
	{
		/// <summary>Banner Image</summary>
		IPublishedContent BannerImage { get; }

		/// <summary>CTA Button</summary>
		string CTabutton { get; }

		/// <summary>CTA Button Link</summary>
		string CTabuttonLink { get; }

		/// <summary>Large Title</summary>
		string LargeTitle { get; }

		/// <summary>Small Heading</summary>
		string Smallheading { get; }
	}

	/// <summary>Banner</summary>
	[PublishedContentModel("banner")]
	public partial class Banner : PublishedContentModel, IBanner
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "banner";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Banner(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Banner, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Banner Image
		///</summary>
		[ImplementPropertyType("bannerImage")]
		public IPublishedContent BannerImage
		{
			get { return GetBannerImage(this); }
		}

		/// <summary>Static getter for Banner Image</summary>
		public static IPublishedContent GetBannerImage(IBanner that) { return that.GetPropertyValue<IPublishedContent>("bannerImage"); }

		///<summary>
		/// CTA Button
		///</summary>
		[ImplementPropertyType("cTAButton")]
		public string CTabutton
		{
			get { return GetCTabutton(this); }
		}

		/// <summary>Static getter for CTA Button</summary>
		public static string GetCTabutton(IBanner that) { return that.GetPropertyValue<string>("cTAButton"); }

		///<summary>
		/// CTA Button Link
		///</summary>
		[ImplementPropertyType("cTAButtonLink")]
		public string CTabuttonLink
		{
			get { return GetCTabuttonLink(this); }
		}

		/// <summary>Static getter for CTA Button Link</summary>
		public static string GetCTabuttonLink(IBanner that) { return that.GetPropertyValue<string>("cTAButtonLink"); }

		///<summary>
		/// Large Title
		///</summary>
		[ImplementPropertyType("largeTitle")]
		public string LargeTitle
		{
			get { return GetLargeTitle(this); }
		}

		/// <summary>Static getter for Large Title</summary>
		public static string GetLargeTitle(IBanner that) { return that.GetPropertyValue<string>("largeTitle"); }

		///<summary>
		/// Small Heading
		///</summary>
		[ImplementPropertyType("smallheading")]
		public string Smallheading
		{
			get { return GetSmallheading(this); }
		}

		/// <summary>Static getter for Small Heading</summary>
		public static string GetSmallheading(IBanner that) { return that.GetPropertyValue<string>("smallheading"); }
	}
}
